version: '3'
services:
  web:
    build: ./app
    ports:
      - "3000:3000"
    restart: always
    links:
      - redis
    depends_on:
      - redis

  redis: 
    image: redis
    ports: 
      - "6379:6379"
