version: '3'
services:
  web:
    build: ./app
    ports:
      - "5001:5000"
    restart: always
    volumes: 
      - ./app:/code/app # bind mount
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy

  redis: 
    image: redis
    ports: 
      - "6379:6379"
    healthcheck:
      test: "redis-cli ping"
